name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]
permissions:
  actions: write
  contents: write
  pull-requests: write
  statuses: write
jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I hereby agree with the Contributor License Agreement') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path-to-signatures: '.github/cla-signatures.json'
          path-to-document: 'https://gist.github.com/alexanderkozlenko/c74ea0910f2a088230478cf7db442a4e'
          branch: 'main'
          allowlist: dependabot[bot]
